### ISSUE TITLE
Ability to change type

### ISSUE THREAD

**Issue by Ojansen** [HoneyTauOverTwo/DSPSeedSearch#1]
Now the default type is set to 'GiantStar', Could we also search different ones, like an O Type or B Type?

**Comment by HoneyTauOverTwo** [comment]
Currently I don't really check the star type, I only search for the biggest Dyson Sphere possible so it happens that GiantStar is always the biggest one available in the galaxy.
But it would be easy to filter for star type during the search, may I ask you why do you want it?

**Comment by Ojansen** [comment]
O type stars may not be the biggest but they almost always have an luminotity of 2 or higher and there can be more then 10 in a galaxy

**Comment by HoneyTauOverTwo** [comment]
Then it is not about changing the star type, but changing for what you want to search for. Instead of the biggest DS radius, search for the highest luminosity.

I guess what one would be most interested in is the biggest power output star, and not necessarily the luminosity or the allowed DS size. I would have look at the code to figure that out, but I have a feeling that the biggest power output will be for the star that allows the biggest DS radius, that is probably what determines the radius in the game code.
