### ISSUE TITLE
Docs Index of csv file

### ISSUE THREAD

**Issue by Ojansen** [HoneyTauOverTwo/DSPSeedSearch#3]
it would be great to see what this means: seed, dysonRadius, planetCount, starName, type, mass, temperature, dysonLuminosity

**Comment by HoneyTauOverTwo** [comment]
I can't tell you that I know it myself. These are just variable names taken directly from the game's code that I thought would be interesting to look at.
When I was coding this I wasn't sure which variable would give me the information that translates to the star that allows the biggest Dyson Sphere to be constructed in-game so I tried those. Turns out it was the most obvious one "dysonRadius" and this is what I use to sort the search.
